"""create products table

Revision ID: 7c9bb98112a3
Revises: 
Create Date: 2026-09-11 11:55:26.202131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '7c9bb98112a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_locale', sa.String(), nullable=False),
    sa.Column('product_title', sa.Text(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_bullet_point', sa.Text(), nullable=True),
    sa.Column('product_brand', sa.String(), nullable=True),
    sa.Column('product_color', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('product_id', 'product_locale')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
